language: node_js
node_js:
    - "0.12"
install:
    - npm install
    - npm install node-gyp jasmine-node
    - node ./install-libxl.js
script:
    - ./node_modules/.bin/node-gyp rebuild
    - LD_LIBRARY_PATH="`pwd`/deps/libxl/lib64" ./node_modules/.bin/jasmine-node ./specs
