language: node_js
node_js:
    - "13"
    - "12"
    - "10"
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
    - npm install
    - npm install jasmine-node
script:
    - LD_LIBRARY_PATH="`pwd`/deps/libxl/lib64" ./node_modules/.bin/jasmine-node ./specs
notifications:
    email:
        on_sucess: change
        on_error: always
        recipients:
            - cnspeckn@googlemail.com
