// Colors
export const COLOR_BLACK: number;
export const COLOR_WHITE: number;
export const COLOR_RED: number;
export const COLOR_BRIGHTGREEN: number;
export const COLOR_BLUE: number;
export const COLOR_YELLOW: number;
export const COLOR_PINK: number;
export const COLOR_TURQUOISE: number;
export const COLOR_DARKRED: number;
export const COLOR_GREEN: number;
export const COLOR_DARKBLUE: number;
export const COLOR_DARKYELLOW: number;
export const COLOR_VIOLET: number;
export const COLOR_TEAL: number;
export const COLOR_GRAY25: number;
export const COLOR_GRAY50: number;
export const COLOR_PERIWINKLE_CF: number;
export const COLOR_PLUM_CF: number;
export const COLOR_IVORY_CF: number;
export const COLOR_LIGHTTURQUOISE_CF: number;
export const COLOR_DARKPURPLE_CF: number;
export const COLOR_CORAL_CF: number;
export const COLOR_OCEANBLUE_CF: number;
export const COLOR_ICEBLUE_CF: number;
export const COLOR_DARKBLUE_CL: number;
export const COLOR_PINK_CL: number;
export const COLOR_YELLOW_CL: number;
export const COLOR_TURQUOISE_CL: number;
export const COLOR_VIOLET_CL: number;
export const COLOR_DARKRED_CL: number;
export const COLOR_TEAL_CL: number;
export const COLOR_BLUE_CL: number;
export const COLOR_SKYBLUE: number;
export const COLOR_LIGHTTURQUOISE: number;
export const COLOR_LIGHTGREEN: number;
export const COLOR_LIGHTYELLOW: number;
export const COLOR_PALEBLUE: number;
export const COLOR_ROSE: number;
export const COLOR_LAVENDER: number;
export const COLOR_TAN: number;
export const COLOR_LIGHTBLUE: number;
export const COLOR_AQUA: number;
export const COLOR_LIME: number;
export const COLOR_GOLD: number;
export const COLOR_LIGHTORANGE: number;
export const COLOR_ORANGE: number;
export const COLOR_BLUEGRAY: number;
export const COLOR_GRAY40: number;
export const COLOR_DARKTEAL: number;
export const COLOR_SEAGREEN: number;
export const COLOR_DARKGREEN: number;
export const COLOR_OLIVEGREEN: number;
export const COLOR_BROWN: number;
export const COLOR_PLUM: number;
export const COLOR_INDIGO: number;
export const COLOR_GRAY80: number;
export const COLOR_DEFAULT_FOREGROUND: number;
export const COLOR_DEFAULT_BACKGROUND: number;
export const COLOR_TOOLTIP: number;
export const COLOR_AUTO: number;

// Number formats
export const NUMFORMAT_GENERAL: number;
export const NUMFORMAT_NUMBER: number;
export const NUMFORMAT_NUMBER_D2: number;
export const NUMFORMAT_NUMBER_SEP: number;
export const NUMFORMAT_NUMBER_SEP_D2: number;
export const NUMFORMAT_CURRENCY_NEGBRA: number;
export const NUMFORMAT_CURRENCY_NEGBRARED: number;
export const NUMFORMAT_CURRENCY_D2_NEGBRA: number;
export const NUMFORMAT_CURRENCY_D2_NEGBRARED: number;
export const NUMFORMAT_PERCENT: number;
export const NUMFORMAT_PERCENT_D2: number;
export const NUMFORMAT_SCIENTIFIC_D2: number;
export const NUMFORMAT_FRACTION_ONEDIG: number;
export const NUMFORMAT_FRACTION_TWODIG: number;
export const NUMFORMAT_DATE: number;
export const NUMFORMAT_CUSTOM_D_MON_YY: number;
export const NUMFORMAT_CUSTOM_D_MON: number;
export const NUMFORMAT_CUSTOM_MON_YY: number;
export const NUMFORMAT_CUSTOM_HMM_AM: number;
export const NUMFORMAT_CUSTOM_HMMSS_AM: number;
export const NUMFORMAT_CUSTOM_HMM: number;
export const NUMFORMAT_CUSTOM_HMMSS: number;
export const NUMFORMAT_CUSTOM_MDYYYY_HMM: number;
export const NUMFORMAT_NUMBER_SEP_NEGBRA: number;
export const NUMFORMAT_NUMBER_SEP_NEGBRARED: number;
export const NUMFORMAT_NUMBER_D2_SEP_NEGBRA: number;
export const NUMFORMAT_NUMBER_D2_SEP_NEGBRARED: number;
export const NUMFORMAT_ACCOUNT: number;
export const NUMFORMAT_ACCOUNTCUR: number;
export const NUMFORMAT_ACCOUNT_D2: number;
export const NUMFORMAT_ACCOUNT_D2_CUR: number;
export const NUMFORMAT_CUSTOM_MMSS: number;
export const NUMFORMAT_CUSTOM_H0MMSS: number;
export const NUMFORMAT_CUSTOM_MMSS0: number;
export const NUMFORMAT_CUSTOM_000P0E_PLUS0: number;
export const NUMFORMAT_TEXT: number;

// Alignment horizontal
export const ALIGNH_GENERAL: number;
export const ALIGNH_LEFT: number;
export const ALIGNH_CENTER: number;
export const ALIGNH_RIGHT: number;
export const ALIGNH_FILL: number;
export const ALIGNH_JUSTIFY: number;
export const ALIGNH_MERGE: number;
export const ALIGNH_DISTRIBUTED: number;

// Alignment vertical
export const ALIGNV_TOP: number;
export const ALIGNV_CENTER: number;
export const ALIGNV_BOTTOM: number;
export const ALIGNV_JUSTIFY: number;
export const ALIGNV_DISTRIBUTED: number;

// Border styles
export const BORDERSTYLE_NONE: number;
export const BORDERSTYLE_THIN: number;
export const BORDERSTYLE_MEDIUM: number;
export const BORDERSTYLE_DASHED: number;
export const BORDERSTYLE_DOTTED: number;
export const BORDERSTYLE_THICK: number;
export const BORDERSTYLE_DOUBLE: number;
export const BORDERSTYLE_HAIR: number;
export const BORDERSTYLE_MEDIUMDASHED: number;
export const BORDERSTYLE_DASHDOT: number;
export const BORDERSTYLE_MEDIUMDASHDOT: number;
export const BORDERSTYLE_DASHDOTDOT: number;
export const BORDERSTYLE_MEDIUMDASHDOTDOT: number;
export const BORDERSTYLE_SLANTDASHDOT: number;

// Border diagonal
export const BORDERDIAGONAL_NONE: number;
export const BORDERDIAGONAL_DOWN: number;
export const BORDERDIAGONAL_UP: number;
export const BORDERDIAGONAL_BOTH: number;

// Fill patterns
export const FILLPATTERN_NONE: number;
export const FILLPATTERN_SOLID: number;
export const FILLPATTERN_GRAY50: number;
export const FILLPATTERN_GRAY75: number;
export const FILLPATTERN_GRAY25: number;
export const FILLPATTERN_HORSTRIPE: number;
export const FILLPATTERN_VERSTRIPE: number;
export const FILLPATTERN_REVDIAGSTRIPE: number;
export const FILLPATTERN_DIAGSTRIPE: number;
export const FILLPATTERN_DIAGCROSSHATCH: number;
export const FILLPATTERN_THICKDIAGCROSSHATCH: number;
export const FILLPATTERN_THINHORSTRIPE: number;
export const FILLPATTERN_THINVERSTRIPE: number;
export const FILLPATTERN_THINREVDIAGSTRIPE: number;
export const FILLPATTERN_THINDIAGSTRIPE: number;
export const FILLPATTERN_THINHORCROSSHATCH: number;
export const FILLPATTERN_THINDIAGCROSSHATCH: number;
export const FILLPATTERN_GRAY12P5: number;
export const FILLPATTERN_GRAY6P25: number;

// Script
export const SCRIPT_NORMAL: number;
export const SCRIPT_SUPER: number;
export const SCRIPT_SUB: number;

// Underline
export const UNDERLINE_NONE: number;
export const UNDERLINE_SINGLE: number;
export const UNDERLINE_DOUBLE: number;
export const UNDERLINE_SINGLEACC: number;
export const UNDERLINE_DOUBLEACC: number;

// Paper sizes
export const PAPER_DEFAULT: number;
export const PAPER_LETTER: number;
export const PAPER_LETTERSMALL: number;
export const PAPER_TABLOID: number;
export const PAPER_LEDGER: number;
export const PAPER_LEGAL: number;
export const PAPER_STATEMENT: number;
export const PAPER_EXECUTIVE: number;
export const PAPER_A3: number;
export const PAPER_A4: number;
export const PAPER_A4SMALL: number;
export const PAPER_A5: number;
export const PAPER_B4: number;
export const PAPER_B5: number;
export const PAPER_FOLIO: number;
export const PAPER_QUATRO: number;
export const PAPER_10x14: number;
export const PAPER_10x17: number;
export const PAPER_NOTE: number;
export const PAPER_ENVELOPE_9: number;
export const PAPER_ENVELOPE_10: number;
export const PAPER_ENVELOPE_11: number;
export const PAPER_ENVELOPE_12: number;
export const PAPER_ENVELOPE_14: number;
export const PAPER_C_SIZE: number;
export const PAPER_D_SIZE: number;
export const PAPER_E_SIZE: number;
export const PAPER_ENVELOPE_DL: number;
export const PAPER_ENVELOPE_C5: number;
export const PAPER_ENVELOPE_C3: number;
export const PAPER_ENVELOPE_C4: number;
export const PAPER_ENVELOPE_C6: number;
export const PAPER_ENVELOPE_C65: number;
export const PAPER_ENVELOPE_B4: number;
export const PAPER_ENVELOPE_B5: number;
export const PAPER_ENVELOPE_B6: number;
export const PAPER_ENVELOPE: number;
export const PAPER_ENVELOPE_MONARCH: number;
export const PAPER_US_ENVELOPE: number;
export const PAPER_FANFOLD: number;
export const PAPER_GERMAN_STD_FANFOLD: number;
export const PAPER_GERMAN_LEGAL_FANFOLD: number;
export const PAPER_B4_ISO: number;
export const PAPER_JAPANESE_POSTCARD: number;
export const PAPER_9x11: number;
export const PAPER_10x11: number;
export const PAPER_15x11: number;
export const PAPER_ENVELOPE_INVITE: number;
export const PAPER_US_LETTER_EXTRA: number;
export const PAPER_US_LEGAL_EXTRA: number;
export const PAPER_US_TABLOID_EXTRA: number;
export const PAPER_A4_EXTRA: number;
export const PAPER_LETTER_TRANSVERSE: number;
export const PAPER_A4_TRANSVERSE: number;
export const PAPER_LETTER_EXTRA_TRANSVERSE: number;
export const PAPER_SUPERA: number;
export const PAPER_SUPERB: number;
export const PAPER_US_LETTER_PLUS: number;
export const PAPER_A4_PLUS: number;
export const PAPER_A5_TRANSVERSE: number;
export const PAPER_B5_TRANSVERSE: number;
export const PAPER_A3_EXTRA: number;
export const PAPER_A5_EXTRA: number;
export const PAPER_B5_EXTRA: number;
export const PAPER_A2: number;
export const PAPER_A3_TRANSVERSE: number;
export const PAPER_A3_EXTRA_TRANSVERSE: number;
export const PAPER_JAPANESE_DOUBLE_POSTCARD: number;
export const PAPER_A6: number;
export const PAPER_JAPANESE_ENVELOPE_KAKU2: number;
export const PAPER_JAPANESE_ENVELOPE_KAKU3: number;
export const PAPER_JAPANESE_ENVELOPE_CHOU3: number;
export const PAPER_JAPANESE_ENVELOPE_CHOU4: number;
export const PAPER_LETTER_ROTATED: number;
export const PAPER_A3_ROTATED: number;
export const PAPER_A4_ROTATED: number;
export const PAPER_A5_ROTATED: number;
export const PAPER_B4_ROTATED: number;
export const PAPER_B5_ROTATED: number;
export const PAPER_JAPANESE_POSTCARD_ROTATED: number;
export const PAPER_DOUBLE_JAPANESE_POSTCARD_ROTATED: number;
export const PAPER_A6_ROTATED: number;
export const PAPER_JAPANESE_ENVELOPE_KAKU2_ROTATED: number;
export const PAPER_JAPANESE_ENVELOPE_KAKU3_ROTATED: number;
export const PAPER_JAPANESE_ENVELOPE_CHOU3_ROTATED: number;
export const PAPER_JAPANESE_ENVELOPE_CHOU4_ROTATED: number;
export const PAPER_B6: number;
export const PAPER_B6_ROTATED: number;
export const PAPER_12x11: number;
export const PAPER_JAPANESE_ENVELOPE_YOU4: number;
export const PAPER_JAPANESE_ENVELOPE_YOU4_ROTATED: number;
export const PAPER_PRC16K: number;
export const PAPER_PRC32K: number;
export const PAPER_PRC32K_BIG: number;
export const PAPER_PRC_ENVELOPE1: number;
export const PAPER_PRC_ENVELOPE2: number;
export const PAPER_PRC_ENVELOPE3: number;
export const PAPER_PRC_ENVELOPE4: number;
export const PAPER_PRC_ENVELOPE5: number;
export const PAPER_PRC_ENVELOPE6: number;
export const PAPER_PRC_ENVELOPE7: number;
export const PAPER_PRC_ENVELOPE8: number;
export const PAPER_PRC_ENVELOPE9: number;
export const PAPER_PRC_ENVELOPE10: number;
export const PAPER_PRC16K_ROTATED: number;
export const PAPER_PRC32K_ROTATED: number;
export const PAPER_PRC32KBIG_ROTATED: number;
export const PAPER_PRC_ENVELOPE1_ROTATED: number;
export const PAPER_PRC_ENVELOPE2_ROTATED: number;
export const PAPER_PRC_ENVELOPE3_ROTATED: number;
export const PAPER_PRC_ENVELOPE4_ROTATED: number;
export const PAPER_PRC_ENVELOPE5_ROTATED: number;
export const PAPER_PRC_ENVELOPE6_ROTATED: number;
export const PAPER_PRC_ENVELOPE7_ROTATED: number;
export const PAPER_PRC_ENVELOPE8_ROTATED: number;
export const PAPER_PRC_ENVELOPE9_ROTATED: number;
export const PAPER_PRC_ENVELOPE10_ROTATED: number;

// Sheet types
export const SHEETTYPE_SHEET: number;
export const SHEETTYPE_CHART: number;
export const SHEETTYPE_UNKNOWN: number;

// Cell types
export const CELLTYPE_EMPTY: number;
export const CELLTYPE_NUMBER: number;
export const CELLTYPE_STRING: number;
export const CELLTYPE_BOOLEAN: number;
export const CELLTYPE_BLANK: number;
export const CELLTYPE_ERROR: number;
export const CELLTYPE_STRICTDATE: number;

// Error types
export const ERRORTYPE_NULL: number;
export const ERRORTYPE_DIV_0: number;
export const ERRORTYPE_VALUE: number;
export const ERRORTYPE_REF: number;
export const ERRORTYPE_NAME: number;
export const ERRORTYPE_NUM: number;
export const ERRORTYPE_NA: number;
export const ERRORTYPE_NOERROR: number;

// Picture types
export const PICTURETYPE_PNG: number;
export const PICTURETYPE_JPEG: number;
export const PICTURETYPE_GIF: number;
export const PICTURETYPE_WMF: number;
export const PICTURETYPE_DIB: number;
export const PICTURETYPE_EMF: number;
export const PICTURETYPE_PICT: number;
export const PICTURETYPE_TIFF: number;
export const PICTURETYPE_SVG: number;
export const PICTURETYPE_ERROR: number;

// Sheet state
export const SHEETSTATE_VISIBLE: number;
export const SHEETSTATE_HIDDEN: number;
export const SHEETSTATE_VERYHIDDEN: number;

// Scope
export const SCOPE_UNDEFINED: number;
export const SCOPE_WORKBOOK: number;

// Position
export const POSITION_MOVE_AND_SIZE: number;
export const POSITION_ONLY_MOVE: number;
export const POSITION_ABSOLUTE: number;

// Operator
export const OPERATOR_EQUAL: number;
export const OPERATOR_GREATER_THAN: number;
export const OPERATOR_GREATER_THAN_OR_EQUAL: number;
export const OPERATOR_LESS_THAN: number;
export const OPERATOR_LESS_THAN_OR_EQUAL: number;
export const OPERATOR_NOT_EQUAL: number;

// Filter
export const FILTER_VALUE: number;
export const FILTER_TOP10: number;
export const FILTER_CUSTOM: number;
export const FILTER_DYNAMIC: number;
export const FILTER_COLOR: number;
export const FILTER_ICON: number;
export const FILTER_EXT: number;
export const FILTER_NOT_SET: number;

// Ignored errors
export const IERR_NO_ERROR: number;
export const IERR_EVAL_ERROR: number;
export const IERR_EMPTY_CELLREF: number;
export const IERR_NUMBER_STORED_AS_TEXT: number;
export const IERR_INCONSIST_RANGE: number;
export const IERR_INCONSIST_FMLA: number;
export const IERR_TWODIG_TEXTYEAR: number;
export const IERR_UNLOCK_FMLA: number;
export const IERR_DATA_VALIDATION: number;

// Protection
export const PROT_DEFAULT: number;
export const PROT_ALL: number;
export const PROT_OBJECTS: number;
export const PROT_SCENARIOS: number;
export const PROT_FORMAT_CELLS: number;
export const PROT_FORMAT_COLUMNS: number;
export const PROT_FORMAT_ROWS: number;
export const PROT_INSERT_COLUMNS: number;
export const PROT_INSERT_ROWS: number;
export const PROT_INSERT_HYPERLINKS: number;
export const PROT_DELETE_COLUMNS: number;
export const PROT_DELETE_ROWS: number;
export const PROT_SEL_LOCKED_CELLS: number;
export const PROT_SORT: number;
export const PROT_AUTOFILTER: number;
export const PROT_PIVOTTABLES: number;
export const PROT_SEL_UNLOCKED_CELLS: number;

// Validation types
export const VALIDATION_TYPE_NONE: number;
export const VALIDATION_TYPE_WHOLE: number;
export const VALIDATION_TYPE_DECIMAL: number;
export const VALIDATION_TYPE_LIST: number;
export const VALIDATION_TYPE_DATE: number;
export const VALIDATION_TYPE_TIME: number;
export const VALIDATION_TYPE_TEXTLENGTH: number;
export const VALIDATION_TYPE_CUSTOM: number;

// Validation operators
export const VALIDATION_OP_BETWEEN: number;
export const VALIDATION_OP_NOTBETWEEN: number;
export const VALIDATION_OP_EQUAL: number;
export const VALIDATION_OP_NOTEQUAL: number;
export const VALIDATION_OP_LESSTHAN: number;
export const VALIDATION_OP_LESSTHANOREQUAL: number;
export const VALIDATION_OP_GREATERTHAN: number;
export const VALIDATION_OP_GREATERTHANOREQUAL: number;

// Validation error styles
export const VALIDATION_ERRSTYLE_STOP: number;
export const VALIDATION_ERRSTYLE_WARNING: number;
export const VALIDATION_ERRSTYLE_INFORMATION: number;

// Calc mode
export const CALCMODE_MANUAL: number;
export const CALCMODE_AUTO: number;
export const CALCMODE_AUTONOTABLE: number;

// Checked type
export const CHECKEDTYPE_UNCHECKED: number;
export const CHECKEDTYPE_CHECKED: number;
export const CHECKEDTYPE_MIXED: number;

// Object types
export const OBJECT_UNKNOWN: number;
export const OBJECT_BUTTON: number;
export const OBJECT_CHECKBOX: number;
export const OBJECT_DROP: number;
export const OBJECT_GBOX: number;
export const OBJECT_LABEL: number;
export const OBJECT_LIST: number;
export const OBJECT_RADIO: number;
export const OBJECT_SCROLL: number;
export const OBJECT_SPIN: number;
export const OBJECT_EDITBOX: number;
export const OBJECT_DIALOG: number;

// Conditional format
export const CFORMAT_BEGINWITH: number;
export const CFORMAT_CONTAINSBLANKS: number;
export const CFORMAT_CONTAINSERRORS: number;
export const CFORMAT_CONTAINSTEXT: number;
export const CFORMAT_DUPLICATEVALUES: number;
export const CFORMAT_ENDSWITH: number;
export const CFORMAT_EXPRESSION: number;
export const CFORMAT_NOTCONTAINSBLANKS: number;
export const CFORMAT_NOTCONTAINSERRORS: number;
export const CFORMAT_NOTCONTAINSTEXT: number;
export const CFORMAT_UNIQUEVALUES: number;

// CF operators
export const CFOPERATOR_LESSTHAN: number;
export const CFOPERATOR_LESSTHANOREQUAL: number;
export const CFOPERATOR_EQUAL: number;
export const CFOPERATOR_NOTEQUAL: number;
export const CFOPERATOR_GREATERTHANOREQUAL: number;
export const CFOPERATOR_GREATERTHAN: number;
export const CFOPERATOR_BETWEEN: number;
export const CFOPERATOR_NOTBETWEEN: number;
export const CFOPERATOR_CONTAINSTEXT: number;
export const CFOPERATOR_NOTCONTAINS: number;
export const CFOPERATOR_BEGINSWITH: number;
export const CFOPERATOR_ENDSWITH: number;

// CF time periods
export const CFTP_LAST7DAYS: number;
export const CFTP_LASTMONTH: number;
export const CFTP_LASTWEEK: number;
export const CFTP_NEXTMONTH: number;
export const CFTP_NEXTWEEK: number;
export const CFTP_THISMONTH: number;
export const CFTP_THISWEEK: number;
export const CFTP_TODAY: number;
export const CFTP_TOMORROW: number;
export const CFTP_YESTERDAY: number;

// CFVO
export const CFVO_MIN: number;
export const CFVO_MAX: number;
export const CFVO_FORMULA: number;
export const CFVO_NUMBER: number;
export const CFVO_PERCENT: number;
export const CFVO_PERCENTILE: number;

// Cell styles
export const CELLSTYLE_NORMAL: number;
export const CELLSTYLE_BAD: number;
export const CELLSTYLE_GOOD: number;
export const CELLSTYLE_NEUTRAL: number;
export const CELLSTYLE_CALC: number;
export const CELLSTYLE_CHECKCELL: number;
export const CELLSTYLE_EXPLANATORY: number;
export const CELLSTYLE_INPUT: number;
export const CELLSTYLE_OUTPUT: number;
export const CELLSTYLE_HYPERLINK: number;
export const CELLSTYLE_LINKEDCELL: number;
export const CELLSTYLE_NOTE: number;
export const CELLSTYLE_WARNING: number;
export const CELLSTYLE_TITLE: number;
export const CELLSTYLE_HEADING1: number;
export const CELLSTYLE_HEADING2: number;
export const CELLSTYLE_HEADING3: number;
export const CELLSTYLE_HEADING4: number;
export const CELLSTYLE_TOTAL: number;
export const CELLSTYLE_20ACCENT1: number;
export const CELLSTYLE_40ACCENT1: number;
export const CELLSTYLE_60ACCENT1: number;
export const CELLSTYLE_ACCENT1: number;
export const CELLSTYLE_20ACCENT2: number;
export const CELLSTYLE_40ACCENT2: number;
export const CELLSTYLE_60ACCENT2: number;
export const CELLSTYLE_ACCENT2: number;
export const CELLSTYLE_20ACCENT3: number;
export const CELLSTYLE_40ACCENT3: number;
export const CELLSTYLE_60ACCENT3: number;
export const CELLSTYLE_ACCENT3: number;
export const CELLSTYLE_20ACCENT4: number;
export const CELLSTYLE_40ACCENT4: number;
export const CELLSTYLE_60ACCENT4: number;
export const CELLSTYLE_ACCENT4: number;
export const CELLSTYLE_20ACCENT5: number;
export const CELLSTYLE_40ACCENT5: number;
export const CELLSTYLE_60ACCENT5: number;
export const CELLSTYLE_ACCENT5: number;
export const CELLSTYLE_20ACCENT6: number;
export const CELLSTYLE_40ACCENT6: number;
export const CELLSTYLE_60ACCENT6: number;
export const CELLSTYLE_ACCENT6: number;
export const CELLSTYLE_COMMA: number;
export const CELLSTYLE_COMMA0: number;
export const CELLSTYLE_CURRENCY: number;
export const CELLSTYLE_CURRENCY0: number;
export const CELLSTYLE_PERCENT: number;

// Error codes
export const ERRCODE_OK: number;
export const ERRCODE_INCORRECTPASSWORD: number;
export const ERRCODE_ROWOUTOFRANGE: number;
export const ERRCODE_COLOUTOFRANGE: number;
export const ERRCODE_INDEXOUTOFRANGE: number;
export const ERRCODE_INDEXNOSENSE: number;
export const ERRCODE_LASTSHEET: number;
export const ERRCODE_SHEETNOTFOUND: number;
export const ERRCODE_NAMECUTOFF: number;
export const ERRCODE_FORMULASYNTAXERROR: number;
export const ERRCODE_SHEETNAMEINVALID: number;
export const ERRCODE_FILENAMEINVALID: number;
export const ERRCODE_NAMEALREADYEXIST: number;
export const ERRCODE_FILENOTAVAILABLE: number;
export const ERRCODE_FILEFORMATNOTSUPPORTED: number;
export const ERRCODE_FUNCNOTSUPPORTEDFORXLS: number;
export const ERRCODE_FUNCNOTSUPPORTEDFORXLSX: number;
export const ERRCODE_LOADEDONLYINFO: number;
export const ERRCODE_FONTSIZEOUTOFRANGE: number;
export const ERRCODE_NOFONTS: number;
export const ERRCODE_STRINGTOOLONG: number;
export const ERRCODE_STRINGNULL: number;
export const ERRCODE_AUTOFILTERNULL: number;
export const ERRCODE_OUTLINELEVELEXCEEDED: number;
export const ERRCODE_LOCALEERROR: number;
export const ERRCODE_XMLERROR: number;
export const ERRCODE_BIFFRECERROR: number;
export const ERRCODE_IOERROR: number;
export const ERRCODE_CONSISTENCYERROR: number;
export const ERRCODE_OUTOFMEMORY: number;
export const ERRCODE_UNKNOWNSTYLE: number;
export const ERRCODE_FORMATNULL: number;
export const ERRCODE_FORMATNOTFOUND: number;
export const ERRCODE_PARENTFORMATNOTFOUND: number;
export const ERRCODE_FONTNOTFOUND: number;
export const ERRCODE_TABLENOTFOUND: number;
export const ERRCODE_RICHSTRINGNOTFOUND: number;
export const ERRCODE_PROPNOTFOUND: number;
export const ERRCODE_UNKNOWNCHAR: number;
export const ERRCODE_CHARNOTALLOWED: number;
export const ERRCODE_CELLNOTFOUND: number;
export const ERRCODE_CELLNOTMERGED: number;
export const ERRCODE_CELLTYPEINCORRECT: number;
export const ERRCODE_HEIGHTTOOHIGH: number;
export const ERRCODE_PICERROR: number;
export const ERRCODE_PICPOSERROR: number;
export const ERRCODE_PICNOTFOUND: number;
export const ERRCODE_PICSIZEINCORRECT: number;
export const ERRCODE_PICOFFSETEXCEED_XY: number;
export const ERRCODE_PICOFFSETEXCEED_Y: number;
export const ERRCODE_PICOFFSETEXCEED_X: number;
export const ERRCODE_NOFREECOLORINDEX: number;
export const ERRCODE_COLORINVALID: number;
export const ERRCODE_PRINTTITLESNOTFOUND: number;
export const ERRCODE_NAMEDRANGENOTFOUND: number;
export const ERRCODE_NAMEDRANGESKIPPED: number;
export const ERRCODE_PAGEBREAKALREADYEXIST: number;
export const ERRCODE_PAGEBREAKNOTFOUND: number;
export const ERRCODE_PAGEBREAKLIMIT: number;
export const ERRCODE_IGNOREDERRALREADYEXIST: number;
export const ERRCODE_OVERLAP: number;
export const ERRCODE_SHEETNOTSPLITTED: number;
export const ERRCODE_DIRENTRYINCORRECTNAME: number;
export const ERRCODE_REFINVALID: number;
export const ERRCODE_REFNOTFOUND: number;
export const ERRCODE_DATEINVALID: number;
export const ERRCODE_XLSERROR: number;
export const ERRCODE_CONVERROR: number;
export const ERRCODE_TOOMANYFORMATS: number;
export const ERRCODE_TOOMANYFONTS: number;
export const ERRCODE_NOSTYLES: number;
export const ERRCODE_NOID: number;
export const ERRCODE_FILTERCOLUMNNULL: number;
export const ERRCODE_FILTERVALUENOTFOUND: number;
export const ERRCODE_FILTERNOTFOUND: number;
export const ERRCODE_DATAVALIDNOTFOUND: number;
export const ERRCODE_ACTIVECELLNOTFOUND: number;
export const ERRCODE_HYPERLINKNOTFOUND: number;
export const ERRCODE_SORTNOTFOUND: number;
export const ERRCODE_CONTROLNOTFOUND: number;
export const ERRCODE_COMMENTNOTFOUND: number;
export const ERRCODE_AUTOFITERROR: number;
export const ERRCODE_VALUEOUTOFRANGE: number;
export const ERRCODE_ZIPERROR: number;
export const ERRCODE_EXCEPTION: number;
export const ERRCODE_TRIALLIMIT: number;

// Table styles
export const TABLESTYLE_NONE: number;
export const TABLESTYLE_LIGHT1: number;
export const TABLESTYLE_LIGHT2: number;
export const TABLESTYLE_LIGHT3: number;
export const TABLESTYLE_LIGHT4: number;
export const TABLESTYLE_LIGHT5: number;
export const TABLESTYLE_LIGHT6: number;
export const TABLESTYLE_LIGHT7: number;
export const TABLESTYLE_LIGHT8: number;
export const TABLESTYLE_LIGHT9: number;
export const TABLESTYLE_LIGHT10: number;
export const TABLESTYLE_LIGHT11: number;
export const TABLESTYLE_LIGHT12: number;
export const TABLESTYLE_LIGHT13: number;
export const TABLESTYLE_LIGHT14: number;
export const TABLESTYLE_LIGHT15: number;
export const TABLESTYLE_LIGHT16: number;
export const TABLESTYLE_LIGHT17: number;
export const TABLESTYLE_LIGHT18: number;
export const TABLESTYLE_LIGHT19: number;
export const TABLESTYLE_LIGHT20: number;
export const TABLESTYLE_LIGHT21: number;
export const TABLESTYLE_MEDIUM1: number;
export const TABLESTYLE_MEDIUM2: number;
export const TABLESTYLE_MEDIUM3: number;
export const TABLESTYLE_MEDIUM4: number;
export const TABLESTYLE_MEDIUM5: number;
export const TABLESTYLE_MEDIUM6: number;
export const TABLESTYLE_MEDIUM7: number;
export const TABLESTYLE_MEDIUM8: number;
export const TABLESTYLE_MEDIUM9: number;
export const TABLESTYLE_MEDIUM10: number;
export const TABLESTYLE_MEDIUM11: number;
export const TABLESTYLE_MEDIUM12: number;
export const TABLESTYLE_MEDIUM13: number;
export const TABLESTYLE_MEDIUM14: number;
export const TABLESTYLE_MEDIUM15: number;
export const TABLESTYLE_MEDIUM16: number;
export const TABLESTYLE_MEDIUM17: number;
export const TABLESTYLE_MEDIUM18: number;
export const TABLESTYLE_MEDIUM19: number;
export const TABLESTYLE_MEDIUM20: number;
export const TABLESTYLE_MEDIUM21: number;
export const TABLESTYLE_MEDIUM22: number;
export const TABLESTYLE_MEDIUM23: number;
export const TABLESTYLE_MEDIUM24: number;
export const TABLESTYLE_MEDIUM25: number;
export const TABLESTYLE_MEDIUM26: number;
export const TABLESTYLE_MEDIUM27: number;
export const TABLESTYLE_MEDIUM28: number;
export const TABLESTYLE_DARK1: number;
export const TABLESTYLE_DARK2: number;
export const TABLESTYLE_DARK3: number;
export const TABLESTYLE_DARK4: number;
export const TABLESTYLE_DARK5: number;
export const TABLESTYLE_DARK6: number;
export const TABLESTYLE_DARK7: number;
export const TABLESTYLE_DARK8: number;
export const TABLESTYLE_DARK9: number;
export const TABLESTYLE_DARK10: number;
export const TABLESTYLE_DARK11: number;

// Book types
export const BOOK_TYPE_XLS: number;
export const BOOK_TYPE_XLSX: number;
