export class FormControl {
    objectType(): number;
    checked(): number;
    setChecked(checked: number): FormControl;
    fmlaGroup(): string;
    setFmlaGroup(fmlaGroup: string): FormControl;
    fmlaLink(): string;
    setFmlaLink(fmlaLink: string): FormControl;
    fmlaRange(): string;
    setFmlaRange(fmlaRange: string): FormControl;
    fmlaTxbx(): string;
    setFmlaTxbx(fmlaTxbx: string): FormControl;
    name(): string;
    linkedCell(): string;
    listFillRange(): string;
    macro(): string;
    altText(): string;
    locked(): boolean;
    defaultSize(): boolean;
    print(): boolean;
    disabled(): boolean;
    item(index: number): string;
    itemSize(): number;
    addItem(value: string): FormControl;
    insertItem(index: number, value: string): FormControl;
    clearItems(): FormControl;
    dropLines(): number;
    setDropLines(lines: number): FormControl;
    dx(): number;
    setDx(dx: number): FormControl;
    firstButton(): boolean;
    setFirstButton(firstButton: boolean): FormControl;
    horiz(): boolean;
    setHoriz(horiz: boolean): FormControl;
    inc(): number;
    setInc(inc: number): FormControl;
    getMax(): number;
    setMax(max: number): FormControl;
    getMin(): number;
    setMin(min: number): FormControl;
    multiSel(): string;
    setMultiSel(multiSel: string): FormControl;
    sel(): number;
    setSel(sel: number): FormControl;
    fromAnchor(): { col: number; colOff: number; row: number; rowOff: number };
    toAnchor(): { col: number; colOff: number; row: number; rowOff: number };
}
