import { Font } from "./font";

export class Format {
    font(): Font;
    setFont(font: Font): Format;
    numFormat(): number;
    setNumFormat(numFormat: number): Format;
    alignH(): number;
    setAlignH(align: number): Format;
    alignV(): number;
    setAlignV(align: number): Format;
    wrap(): boolean;
    setWrap(wrap?: boolean): Format;
    rotation(): number;
    setRotation(rotation: number): Format;
    indent(): number;
    setIndent(indent: number): Format;
    shrinkToFit(): boolean;
    setShrinkToFit(shrinkToFit?: boolean): Format;
    setBorderStyle(style: number): Format;
    borderLeft(): number;
    setBorderLeft(style: number): Format;
    borderRight(): number;
    setBorderRight(style: number): Format;
    borderTop(): number;
    setBorderTop(style: number): Format;
    borderBottom(): number;
    setBorderBottom(style: number): Format;
    setBorderColor(color: number): Format;
    borderLeftColor(): number;
    setBorderLeftColor(color: number): Format;
    borderRightColor(): number;
    setBorderRightColor(color: number): Format;
    borderTopColor(): number;
    setBorderTopColor(color: number): Format;
    borderBottomColor(): number;
    setBorderBottomColor(color: number): Format;
    borderDiagonal(): number;
    setBorderDiagonal(border: number): Format;
    borderDiagonalStyle(): number;
    setBorderDiagonalStyle(style: number): Format;
    borderDiagonalColor(): number;
    setBorderDiagonalColor(color: number): Format;
    fillPattern(): number;
    setFillPattern(pattern: number): Format;
    patternForegroundColor(): number;
    setPatternForegroundColor(color: number): Format;
    patternBackgroundColor(): number;
    setPatternBackgroundColor(color: number): Format;
    locked(): boolean;
    setLocked(locked?: boolean): Format;
    hidden(): boolean;
    setHidden(hidden?: boolean): Format;
}
