/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2025 Christian Speckner <cnspeckn@googlemail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "enum.h"

using namespace libxl;

void node_libxl::DefineEnums(v8::Local<v8::Object> exports) {
    // CellStyle
    NODE_DEFINE_CONSTANT(exports, COLOR_BLACK);
    NODE_DEFINE_CONSTANT(exports, COLOR_WHITE);
    NODE_DEFINE_CONSTANT(exports, COLOR_RED);
    NODE_DEFINE_CONSTANT(exports, COLOR_BRIGHTGREEN);
    NODE_DEFINE_CONSTANT(exports, COLOR_BLUE);
    NODE_DEFINE_CONSTANT(exports, COLOR_YELLOW);
    NODE_DEFINE_CONSTANT(exports, COLOR_PINK);
    NODE_DEFINE_CONSTANT(exports, COLOR_TURQUOISE);
    NODE_DEFINE_CONSTANT(exports, COLOR_DARKRED);
    NODE_DEFINE_CONSTANT(exports, COLOR_GREEN);
    NODE_DEFINE_CONSTANT(exports, COLOR_DARKBLUE);
    NODE_DEFINE_CONSTANT(exports, COLOR_DARKYELLOW);
    NODE_DEFINE_CONSTANT(exports, COLOR_VIOLET);
    NODE_DEFINE_CONSTANT(exports, COLOR_TEAL);
    NODE_DEFINE_CONSTANT(exports, COLOR_GRAY25);
    NODE_DEFINE_CONSTANT(exports, COLOR_GRAY50);
    NODE_DEFINE_CONSTANT(exports, COLOR_PERIWINKLE_CF);
    NODE_DEFINE_CONSTANT(exports, COLOR_PLUM_CF);
    NODE_DEFINE_CONSTANT(exports, COLOR_IVORY_CF);
    NODE_DEFINE_CONSTANT(exports, COLOR_LIGHTTURQUOISE_CF);
    NODE_DEFINE_CONSTANT(exports, COLOR_DARKPURPLE_CF);
    NODE_DEFINE_CONSTANT(exports, COLOR_CORAL_CF);
    NODE_DEFINE_CONSTANT(exports, COLOR_OCEANBLUE_CF);
    NODE_DEFINE_CONSTANT(exports, COLOR_ICEBLUE_CF);
    NODE_DEFINE_CONSTANT(exports, COLOR_DARKBLUE_CL);
    NODE_DEFINE_CONSTANT(exports, COLOR_PINK_CL);
    NODE_DEFINE_CONSTANT(exports, COLOR_YELLOW_CL);
    NODE_DEFINE_CONSTANT(exports, COLOR_TURQUOISE_CL);
    NODE_DEFINE_CONSTANT(exports, COLOR_VIOLET_CL);
    NODE_DEFINE_CONSTANT(exports, COLOR_DARKRED_CL);
    NODE_DEFINE_CONSTANT(exports, COLOR_TEAL_CL);
    NODE_DEFINE_CONSTANT(exports, COLOR_BLUE_CL);
    NODE_DEFINE_CONSTANT(exports, COLOR_SKYBLUE);
    NODE_DEFINE_CONSTANT(exports, COLOR_LIGHTTURQUOISE);
    NODE_DEFINE_CONSTANT(exports, COLOR_LIGHTGREEN);
    NODE_DEFINE_CONSTANT(exports, COLOR_LIGHTYELLOW);
    NODE_DEFINE_CONSTANT(exports, COLOR_PALEBLUE);
    NODE_DEFINE_CONSTANT(exports, COLOR_ROSE);
    NODE_DEFINE_CONSTANT(exports, COLOR_LAVENDER);
    NODE_DEFINE_CONSTANT(exports, COLOR_TAN);
    NODE_DEFINE_CONSTANT(exports, COLOR_LIGHTBLUE);
    NODE_DEFINE_CONSTANT(exports, COLOR_AQUA);
    NODE_DEFINE_CONSTANT(exports, COLOR_LIME);
    NODE_DEFINE_CONSTANT(exports, COLOR_GOLD);
    NODE_DEFINE_CONSTANT(exports, COLOR_LIGHTORANGE);
    NODE_DEFINE_CONSTANT(exports, COLOR_ORANGE);
    NODE_DEFINE_CONSTANT(exports, COLOR_BLUEGRAY);
    NODE_DEFINE_CONSTANT(exports, COLOR_GRAY40);
    NODE_DEFINE_CONSTANT(exports, COLOR_DARKTEAL);
    NODE_DEFINE_CONSTANT(exports, COLOR_SEAGREEN);
    NODE_DEFINE_CONSTANT(exports, COLOR_DARKGREEN);
    NODE_DEFINE_CONSTANT(exports, COLOR_OLIVEGREEN);
    NODE_DEFINE_CONSTANT(exports, COLOR_BROWN);
    NODE_DEFINE_CONSTANT(exports, COLOR_PLUM);
    NODE_DEFINE_CONSTANT(exports, COLOR_INDIGO);
    NODE_DEFINE_CONSTANT(exports, COLOR_GRAY80);
    NODE_DEFINE_CONSTANT(exports, COLOR_DEFAULT_FOREGROUND);
    NODE_DEFINE_CONSTANT(exports, COLOR_DEFAULT_BACKGROUND);
    NODE_DEFINE_CONSTANT(exports, COLOR_TOOLTIP);
    NODE_DEFINE_CONSTANT(exports, COLOR_NONE);
    NODE_DEFINE_CONSTANT(exports, COLOR_AUTO);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_GENERAL);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_NUMBER);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_NUMBER_D2);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_NUMBER_SEP);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_NUMBER_SEP_D2);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CURRENCY_NEGBRA);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CURRENCY_NEGBRARED);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CURRENCY_D2_NEGBRA);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CURRENCY_D2_NEGBRARED);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_PERCENT);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_PERCENT_D2);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_SCIENTIFIC_D2);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_FRACTION_ONEDIG);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_FRACTION_TWODIG);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_DATE);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_D_MON_YY);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_D_MON);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_MON_YY);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_HMM_AM);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_HMMSS_AM);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_HMM);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_HMMSS);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_MDYYYY_HMM);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_NUMBER_SEP_NEGBRA);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_NUMBER_SEP_NEGBRARED);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_NUMBER_D2_SEP_NEGBRA);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_NUMBER_D2_SEP_NEGBRARED);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_ACCOUNT);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_ACCOUNTCUR);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_ACCOUNT_D2);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_ACCOUNT_D2_CUR);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_MMSS);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_H0MMSS);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_MMSS0);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_CUSTOM_000P0E_PLUS0);
    NODE_DEFINE_CONSTANT(exports, NUMFORMAT_TEXT);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, ALIGNH_GENERAL);
    NODE_DEFINE_CONSTANT(exports, ALIGNH_LEFT);
    NODE_DEFINE_CONSTANT(exports, ALIGNH_CENTER);
    NODE_DEFINE_CONSTANT(exports, ALIGNH_RIGHT);
    NODE_DEFINE_CONSTANT(exports, ALIGNH_FILL);
    NODE_DEFINE_CONSTANT(exports, ALIGNH_JUSTIFY);
    NODE_DEFINE_CONSTANT(exports, ALIGNH_MERGE);
    NODE_DEFINE_CONSTANT(exports, ALIGNH_DISTRIBUTED);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, ALIGNV_TOP);
    NODE_DEFINE_CONSTANT(exports, ALIGNV_CENTER);
    NODE_DEFINE_CONSTANT(exports, ALIGNV_BOTTOM);
    NODE_DEFINE_CONSTANT(exports, ALIGNV_JUSTIFY);
    NODE_DEFINE_CONSTANT(exports, ALIGNV_DISTRIBUTED);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_NONE);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_THIN);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_MEDIUM);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_DASHED);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_DOTTED);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_THICK);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_DOUBLE);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_HAIR);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_MEDIUMDASHED);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_DASHDOT);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_MEDIUMDASHDOT);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_DASHDOTDOT);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_MEDIUMDASHDOTDOT);
    NODE_DEFINE_CONSTANT(exports, BORDERSTYLE_SLANTDASHDOT);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, BORDERDIAGONAL_NONE);
    NODE_DEFINE_CONSTANT(exports, BORDERDIAGONAL_DOWN);
    NODE_DEFINE_CONSTANT(exports, BORDERDIAGONAL_UP);
    NODE_DEFINE_CONSTANT(exports, BORDERDIAGONAL_BOTH);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_NONE);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_SOLID);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_GRAY50);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_GRAY75);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_GRAY25);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_HORSTRIPE);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_VERSTRIPE);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_REVDIAGSTRIPE);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_DIAGSTRIPE);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_DIAGCROSSHATCH);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_THICKDIAGCROSSHATCH);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_THINHORSTRIPE);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_THINVERSTRIPE);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_THINREVDIAGSTRIPE);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_THINDIAGSTRIPE);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_THINHORCROSSHATCH);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_THINDIAGCROSSHATCH);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_GRAY12P5);
    NODE_DEFINE_CONSTANT(exports, FILLPATTERN_GRAY6P25);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, SCRIPT_NORMAL);
    NODE_DEFINE_CONSTANT(exports, SCRIPT_SUPER);
    NODE_DEFINE_CONSTANT(exports, SCRIPT_SUB);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, UNDERLINE_NONE);
    NODE_DEFINE_CONSTANT(exports, UNDERLINE_SINGLE);
    NODE_DEFINE_CONSTANT(exports, UNDERLINE_DOUBLE);
    NODE_DEFINE_CONSTANT(exports, UNDERLINE_SINGLEACC);
    NODE_DEFINE_CONSTANT(exports, UNDERLINE_DOUBLEACC);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, PAPER_DEFAULT);
    NODE_DEFINE_CONSTANT(exports, PAPER_LETTER);
    NODE_DEFINE_CONSTANT(exports, PAPER_LETTERSMALL);
    NODE_DEFINE_CONSTANT(exports, PAPER_TABLOID);
    NODE_DEFINE_CONSTANT(exports, PAPER_LEDGER);
    NODE_DEFINE_CONSTANT(exports, PAPER_LEGAL);
    NODE_DEFINE_CONSTANT(exports, PAPER_STATEMENT);
    NODE_DEFINE_CONSTANT(exports, PAPER_EXECUTIVE);
    NODE_DEFINE_CONSTANT(exports, PAPER_A3);
    NODE_DEFINE_CONSTANT(exports, PAPER_A4);
    NODE_DEFINE_CONSTANT(exports, PAPER_A4SMALL);
    NODE_DEFINE_CONSTANT(exports, PAPER_A5);
    NODE_DEFINE_CONSTANT(exports, PAPER_B4);
    NODE_DEFINE_CONSTANT(exports, PAPER_B5);
    NODE_DEFINE_CONSTANT(exports, PAPER_FOLIO);
    NODE_DEFINE_CONSTANT(exports, PAPER_QUATRO);
    NODE_DEFINE_CONSTANT(exports, PAPER_10x14);
    NODE_DEFINE_CONSTANT(exports, PAPER_10x17);
    NODE_DEFINE_CONSTANT(exports, PAPER_NOTE);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_9);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_10);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_11);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_12);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_14);
    NODE_DEFINE_CONSTANT(exports, PAPER_C_SIZE);
    NODE_DEFINE_CONSTANT(exports, PAPER_D_SIZE);
    NODE_DEFINE_CONSTANT(exports, PAPER_E_SIZE);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_DL);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_C5);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_C3);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_C4);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_C6);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_C65);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_B4);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_B5);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_B6);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_MONARCH);
    NODE_DEFINE_CONSTANT(exports, PAPER_US_ENVELOPE);
    NODE_DEFINE_CONSTANT(exports, PAPER_FANFOLD);
    NODE_DEFINE_CONSTANT(exports, PAPER_GERMAN_STD_FANFOLD);
    NODE_DEFINE_CONSTANT(exports, PAPER_GERMAN_LEGAL_FANFOLD);
    NODE_DEFINE_CONSTANT(exports, PAPER_B4_ISO);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_POSTCARD);
    NODE_DEFINE_CONSTANT(exports, PAPER_9x11);
    NODE_DEFINE_CONSTANT(exports, PAPER_10x11);
    NODE_DEFINE_CONSTANT(exports, PAPER_15x11);
    NODE_DEFINE_CONSTANT(exports, PAPER_ENVELOPE_INVITE);
    NODE_DEFINE_CONSTANT(exports, PAPER_US_LETTER_EXTRA);
    NODE_DEFINE_CONSTANT(exports, PAPER_US_LEGAL_EXTRA);
    NODE_DEFINE_CONSTANT(exports, PAPER_US_TABLOID_EXTRA);
    NODE_DEFINE_CONSTANT(exports, PAPER_A4_EXTRA);
    NODE_DEFINE_CONSTANT(exports, PAPER_LETTER_TRANSVERSE);
    NODE_DEFINE_CONSTANT(exports, PAPER_A4_TRANSVERSE);
    NODE_DEFINE_CONSTANT(exports, PAPER_LETTER_EXTRA_TRANSVERSE);
    NODE_DEFINE_CONSTANT(exports, PAPER_SUPERA);
    NODE_DEFINE_CONSTANT(exports, PAPER_SUPERB);
    NODE_DEFINE_CONSTANT(exports, PAPER_US_LETTER_PLUS);
    NODE_DEFINE_CONSTANT(exports, PAPER_A4_PLUS);
    NODE_DEFINE_CONSTANT(exports, PAPER_A5_TRANSVERSE);
    NODE_DEFINE_CONSTANT(exports, PAPER_B5_TRANSVERSE);
    NODE_DEFINE_CONSTANT(exports, PAPER_A3_EXTRA);
    NODE_DEFINE_CONSTANT(exports, PAPER_A5_EXTRA);
    NODE_DEFINE_CONSTANT(exports, PAPER_B5_EXTRA);
    NODE_DEFINE_CONSTANT(exports, PAPER_A2);
    NODE_DEFINE_CONSTANT(exports, PAPER_A3_TRANSVERSE);
    NODE_DEFINE_CONSTANT(exports, PAPER_A3_EXTRA_TRANSVERSE);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_DOUBLE_POSTCARD);
    NODE_DEFINE_CONSTANT(exports, PAPER_A6);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_KAKU2);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_KAKU3);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_CHOU3);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_CHOU4);
    NODE_DEFINE_CONSTANT(exports, PAPER_LETTER_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_A3_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_A4_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_A5_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_B4_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_B5_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_POSTCARD_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_DOUBLE_JAPANESE_POSTCARD_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_A6_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_KAKU2_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_KAKU3_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_CHOU3_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_CHOU4_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_B6);
    NODE_DEFINE_CONSTANT(exports, PAPER_B6_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_12x11);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_YOU4);
    NODE_DEFINE_CONSTANT(exports, PAPER_JAPANESE_ENVELOPE_YOU4_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC16K);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC32K);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC32K_BIG);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE1);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE2);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE3);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE4);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE5);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE6);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE7);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE8);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE9);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE10);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC16K_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC32K_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC32KBIG_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE1_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE2_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE3_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE4_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE5_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE6_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE7_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE8_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE9_ROTATED);
    NODE_DEFINE_CONSTANT(exports, PAPER_PRC_ENVELOPE10_ROTATED);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, SHEETTYPE_SHEET);
    NODE_DEFINE_CONSTANT(exports, SHEETTYPE_CHART);
    NODE_DEFINE_CONSTANT(exports, SHEETTYPE_UNKNOWN);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, CELLTYPE_EMPTY);
    NODE_DEFINE_CONSTANT(exports, CELLTYPE_NUMBER);
    NODE_DEFINE_CONSTANT(exports, CELLTYPE_STRING);
    NODE_DEFINE_CONSTANT(exports, CELLTYPE_BOOLEAN);
    NODE_DEFINE_CONSTANT(exports, CELLTYPE_BLANK);
    NODE_DEFINE_CONSTANT(exports, CELLTYPE_ERROR);
    NODE_DEFINE_CONSTANT(exports, CELLTYPE_STRICTDATE);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, ERRORTYPE_NULL);
    NODE_DEFINE_CONSTANT(exports, ERRORTYPE_DIV_0);
    NODE_DEFINE_CONSTANT(exports, ERRORTYPE_VALUE);
    NODE_DEFINE_CONSTANT(exports, ERRORTYPE_REF);
    NODE_DEFINE_CONSTANT(exports, ERRORTYPE_NAME);
    NODE_DEFINE_CONSTANT(exports, ERRORTYPE_NUM);
    NODE_DEFINE_CONSTANT(exports, ERRORTYPE_NA);
    NODE_DEFINE_CONSTANT(exports, ERRORTYPE_NOERROR);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_PNG);
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_JPEG);
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_GIF);
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_WMF);
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_DIB);
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_EMF);
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_PICT);
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_TIFF);
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_SVG);
    NODE_DEFINE_CONSTANT(exports, PICTURETYPE_ERROR);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, SHEETSTATE_VISIBLE);
    NODE_DEFINE_CONSTANT(exports, SHEETSTATE_HIDDEN);
    NODE_DEFINE_CONSTANT(exports, SHEETSTATE_VERYHIDDEN);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, SCOPE_UNDEFINED);
    NODE_DEFINE_CONSTANT(exports, SCOPE_WORKBOOK);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, POSITION_MOVE_AND_SIZE);
    NODE_DEFINE_CONSTANT(exports, POSITION_ONLY_MOVE);
    NODE_DEFINE_CONSTANT(exports, POSITION_ABSOLUTE);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, OPERATOR_EQUAL);
    NODE_DEFINE_CONSTANT(exports, OPERATOR_GREATER_THAN);
    NODE_DEFINE_CONSTANT(exports, OPERATOR_GREATER_THAN_OR_EQUAL);
    NODE_DEFINE_CONSTANT(exports, OPERATOR_LESS_THAN);
    NODE_DEFINE_CONSTANT(exports, OPERATOR_LESS_THAN_OR_EQUAL);
    NODE_DEFINE_CONSTANT(exports, OPERATOR_NOT_EQUAL);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, FILTER_VALUE);
    NODE_DEFINE_CONSTANT(exports, FILTER_TOP10);
    NODE_DEFINE_CONSTANT(exports, FILTER_CUSTOM);
    NODE_DEFINE_CONSTANT(exports, FILTER_DYNAMIC);
    NODE_DEFINE_CONSTANT(exports, FILTER_COLOR);
    NODE_DEFINE_CONSTANT(exports, FILTER_ICON);
    NODE_DEFINE_CONSTANT(exports, FILTER_EXT);
    NODE_DEFINE_CONSTANT(exports, FILTER_NOT_SET);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, IERR_NO_ERROR);
    NODE_DEFINE_CONSTANT(exports, IERR_EVAL_ERROR);
    NODE_DEFINE_CONSTANT(exports, IERR_EMPTY_CELLREF);
    NODE_DEFINE_CONSTANT(exports, IERR_NUMBER_STORED_AS_TEXT);
    NODE_DEFINE_CONSTANT(exports, IERR_INCONSIST_RANGE);
    NODE_DEFINE_CONSTANT(exports, IERR_INCONSIST_FMLA);
    NODE_DEFINE_CONSTANT(exports, IERR_TWODIG_TEXTYEAR);
    NODE_DEFINE_CONSTANT(exports, IERR_UNLOCK_FMLA);
    NODE_DEFINE_CONSTANT(exports, IERR_DATA_VALIDATION);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, PROT_DEFAULT);
    NODE_DEFINE_CONSTANT(exports, PROT_ALL);
    NODE_DEFINE_CONSTANT(exports, PROT_OBJECTS);
    NODE_DEFINE_CONSTANT(exports, PROT_SCENARIOS);
    NODE_DEFINE_CONSTANT(exports, PROT_FORMAT_CELLS);
    NODE_DEFINE_CONSTANT(exports, PROT_FORMAT_COLUMNS);
    NODE_DEFINE_CONSTANT(exports, PROT_FORMAT_ROWS);
    NODE_DEFINE_CONSTANT(exports, PROT_INSERT_COLUMNS);
    NODE_DEFINE_CONSTANT(exports, PROT_INSERT_ROWS);
    NODE_DEFINE_CONSTANT(exports, PROT_INSERT_HYPERLINKS);
    NODE_DEFINE_CONSTANT(exports, PROT_DELETE_COLUMNS);
    NODE_DEFINE_CONSTANT(exports, PROT_DELETE_ROWS);
    NODE_DEFINE_CONSTANT(exports, PROT_SEL_LOCKED_CELLS);
    NODE_DEFINE_CONSTANT(exports, PROT_SORT);
    NODE_DEFINE_CONSTANT(exports, PROT_AUTOFILTER);
    NODE_DEFINE_CONSTANT(exports, PROT_PIVOTTABLES);
    NODE_DEFINE_CONSTANT(exports, PROT_SEL_UNLOCKED_CELLS);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, VALIDATION_TYPE_NONE);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_TYPE_WHOLE);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_TYPE_DECIMAL);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_TYPE_LIST);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_TYPE_DATE);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_TYPE_TIME);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_TYPE_TEXTLENGTH);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_TYPE_CUSTOM);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, VALIDATION_OP_BETWEEN);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_OP_NOTBETWEEN);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_OP_EQUAL);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_OP_NOTEQUAL);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_OP_LESSTHAN);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_OP_LESSTHANOREQUAL);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_OP_GREATERTHAN);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_OP_GREATERTHANOREQUAL);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, VALIDATION_ERRSTYLE_STOP);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_ERRSTYLE_WARNING);
    NODE_DEFINE_CONSTANT(exports, VALIDATION_ERRSTYLE_INFORMATION);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, CALCMODE_MANUAL);
    NODE_DEFINE_CONSTANT(exports, CALCMODE_AUTO);
    NODE_DEFINE_CONSTANT(exports, CALCMODE_AUTONOTABLE);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, CHECKEDTYPE_UNCHECKED);
    NODE_DEFINE_CONSTANT(exports, CHECKEDTYPE_CHECKED);
    NODE_DEFINE_CONSTANT(exports, CHECKEDTYPE_MIXED);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, OBJECT_UNKNOWN);
    NODE_DEFINE_CONSTANT(exports, OBJECT_BUTTON);
    NODE_DEFINE_CONSTANT(exports, OBJECT_CHECKBOX);
    NODE_DEFINE_CONSTANT(exports, OBJECT_DROP);
    NODE_DEFINE_CONSTANT(exports, OBJECT_GBOX);
    NODE_DEFINE_CONSTANT(exports, OBJECT_LABEL);
    NODE_DEFINE_CONSTANT(exports, OBJECT_LIST);
    NODE_DEFINE_CONSTANT(exports, OBJECT_RADIO);
    NODE_DEFINE_CONSTANT(exports, OBJECT_SCROLL);
    NODE_DEFINE_CONSTANT(exports, OBJECT_SPIN);
    NODE_DEFINE_CONSTANT(exports, OBJECT_EDITBOX);
    NODE_DEFINE_CONSTANT(exports, OBJECT_DIALOG);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, CFORMAT_BEGINWITH);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_CONTAINSBLANKS);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_CONTAINSERRORS);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_CONTAINSTEXT);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_DUPLICATEVALUES);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_ENDSWITH);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_EXPRESSION);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_NOTCONTAINSBLANKS);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_NOTCONTAINSERRORS);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_NOTCONTAINSTEXT);
    NODE_DEFINE_CONSTANT(exports, CFORMAT_UNIQUEVALUES);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_LESSTHAN);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_LESSTHANOREQUAL);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_EQUAL);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_NOTEQUAL);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_GREATERTHANOREQUAL);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_GREATERTHAN);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_BETWEEN);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_NOTBETWEEN);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_CONTAINSTEXT);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_NOTCONTAINS);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_BEGINSWITH);
    NODE_DEFINE_CONSTANT(exports, CFOPERATOR_ENDSWITH);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, CFTP_LAST7DAYS);
    NODE_DEFINE_CONSTANT(exports, CFTP_LASTMONTH);
    NODE_DEFINE_CONSTANT(exports, CFTP_LASTWEEK);
    NODE_DEFINE_CONSTANT(exports, CFTP_NEXTMONTH);
    NODE_DEFINE_CONSTANT(exports, CFTP_NEXTWEEK);
    NODE_DEFINE_CONSTANT(exports, CFTP_THISMONTH);
    NODE_DEFINE_CONSTANT(exports, CFTP_THISWEEK);
    NODE_DEFINE_CONSTANT(exports, CFTP_TODAY);
    NODE_DEFINE_CONSTANT(exports, CFTP_TOMORROW);
    NODE_DEFINE_CONSTANT(exports, CFTP_YESTERDAY);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, CFVO_MIN);
    NODE_DEFINE_CONSTANT(exports, CFVO_MAX);
    NODE_DEFINE_CONSTANT(exports, CFVO_FORMULA);
    NODE_DEFINE_CONSTANT(exports, CFVO_NUMBER);
    NODE_DEFINE_CONSTANT(exports, CFVO_PERCENT);
    NODE_DEFINE_CONSTANT(exports, CFVO_PERCENTILE);

    // CellStyle
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_NORMAL);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_BAD);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_GOOD);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_NEUTRAL);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_CALC);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_CHECKCELL);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_EXPLANATORY);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_INPUT);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_OUTPUT);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_HYPERLINK);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_LINKEDCELL);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_NOTE);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_WARNING);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_TITLE);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_HEADING1);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_HEADING2);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_HEADING3);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_HEADING4);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_TOTAL);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_20ACCENT1);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_40ACCENT1);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_60ACCENT1);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_ACCENT1);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_20ACCENT2);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_40ACCENT2);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_60ACCENT2);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_ACCENT2);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_20ACCENT3);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_40ACCENT3);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_60ACCENT3);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_ACCENT3);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_20ACCENT4);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_40ACCENT4);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_60ACCENT4);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_ACCENT4);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_20ACCENT5);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_40ACCENT5);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_60ACCENT5);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_ACCENT5);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_20ACCENT6);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_40ACCENT6);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_60ACCENT6);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_ACCENT6);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_COMMA);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_COMMA0);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_CURRENCY);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_CURRENCY0);
    NODE_DEFINE_CONSTANT(exports, CELLSTYLE_PERCENT);
}